INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Hani', 'Farran', 'Faculty','Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Ismail', 'Taqi', 'Faculty','Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Marian', 'Deaconescu', 'Faculty','Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Michael', 'Johnson', 'Faculty','Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Nejib', 'Smaoui', 'Faculty','Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Salem', 'Al-Yaqoub', 'Faculty','Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Abdullah', 'Alazemi', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Ahmad', 'Karaballi', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Albert', 'Borbely', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Ali ', 'Kanso', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Anton', 'Betten', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Aurelian', 'Bejancu', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Bader ', 'Al-Shammary', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Boudjemaa', 'Anchouche', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Boumediene', 'Chentouf', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Fares', 'Alazemi', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Fathi', 'Saidi', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Fuat', 'Gurcan', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Khaled', 'Qazaqzeh', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Khalifa', 'Es-Sebaiy', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Latif', 'Hanna', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Mamad', 'Ghebleh', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Milica', 'Anđelić', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Zafer', 'Mahmud', 'Faculty','Associate Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Abdulaziz', 'Alsenafi', 'Faculty','Assistant Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Abdullah', 'Alshammari', 'Faculty','Assistant Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Abdelhameed', 'Abdo', 'Faculty','Assistant Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Ahood', 'Al-Jasser', 'Faculty','Assistant Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Ameena', 'Alzaidan', 'Faculty','Assistant Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Hamid', 'Said', 'Faculty','Assistant Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Hessah', 'Al-Motairi', 'Faculty','Assistant Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Kyriakos', 'Papadopoulos', 'Faculty','Assistant Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Maryam', 'Alkandari', 'Faculty','Assistant Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Mishari', 'Al-Foraih', 'Faculty','Assistant Professor',410);
INSERT INTO Employee (fname, lname, main_rank, sub_rank, department_id) VALUES  ('Saleh', 'Baqer', 'Faculty','Assistant Professor',410);
  


INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Abdulrahman', 'Mubarak', 'Teaching Assistant', 410);
INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Adnan', 'Al-Sayed', 'Teaching Assistant', 410);
INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Alaa', 'Alqaderi', 'Teaching Assistant', 410);
INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Amal', 'Alrashdan', 'Teaching Assistant', 410);
INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Ayman', 'EzzElarab', 'Teaching Assistant', 410);
INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Baba', 'Amoro', 'Teaching Assistant', 410);
INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Hameed', 'Al-Fahad', 'Teaching Assistant', 410);
INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Maale', 'Al-Motairi', 'Teaching Assistant', 410);
INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Mayada', 'Yousif', 'Teaching Assistant', 410);
INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Muna', 'Aljazzaf', 'Teaching Assistant', 410);
INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Rayouf', 'Alsahli', 'Teaching Assistant', 410);
INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Samer', 'Al-Sahhar', 'Teaching Assistant', 410);
INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Shorouq', 'Al-Ghunaim', 'Teaching Assistant', 410);
INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Wafa', 'Abdulrahman', 'Teaching Assistant', 410);
INSERT INTO Employee (fname, lname, main_rank, department_id) VALUES  ('Yousef', 'Alenazi', 'Teaching Assistant', 410);
