INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (144, 'NULL');
INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (145, 'Portland State University');
INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (146, 'Kuwait University');
INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (147, 'Kuwait University');
INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (148, 'Kuwait University');
INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (149, 'Kuwait University');
INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (150, 'Kuwait University');
INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (151, 'NULL');
INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (152, 'NULL');
INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (153, 'NULL');
INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (154, 'NULL');
INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (155, 'NULL');
INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (156, 'NULL');
INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (157, 'NULL');
INSERT INTO Teaching_Assistant (faculty_id, masters_from) VALUES (158, 'Kuwait University');
