# Generated by Django 4.0.4 on 2022-05-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='exams_difficulty',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overall_rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='teaching_quality',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='userfacultyrev',
            name='downvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userfacultyrev',
            name='report_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userfacultyrev',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
