# Generated by Django 3.2.5 on 2022-05-04 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfacultyrev',
            name='downvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userfacultyrev',
            name='upvotes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
