# Generated by Django 3.2.5 on 2022-03-18 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='DeptGeneralcomments',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='FacultyCourse',
        ),
        migrations.DeleteModel(
            name='FacultyMiscellaneous',
        ),
        migrations.DeleteModel(
            name='FacultyPersonality',
        ),
        migrations.DeleteModel(
            name='FacultyWorkload',
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
        migrations.DeleteModel(
            name='SimilarCourses',
        ),
        migrations.DeleteModel(
            name='SimilarFaculty',
        ),
        migrations.DeleteModel(
            name='TeachingAssistant',
        ),
        migrations.DeleteModel(
            name='UserCourseRev',
        ),
        migrations.DeleteModel(
            name='UserDept',
        ),
        migrations.DeleteModel(
            name='UserFacultyRev',
        ),
    ]
