# Generated by Django 3.2.5 on 2022-04-25 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220425_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='rank',
            new_name='main_rank',
        ),
    ]
