# Generated by Django 3.2.5 on 2022-04-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_accountemailaddress_accountemailconfirmation_languageinstructor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReactCourserev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.IntegerField(blank=True, null=True)),
                ('downvote', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_react_courseRev',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserReactFacultyrev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.IntegerField(blank=True, null=True)),
                ('downvote', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_react_facultyRev',
                'managed': False,
            },
        ),
    ]
