# Generated by Django 4.0.3 on 2022-05-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userfacultyrev_downvotes_and_more'),
        ('main', '0003_auto_20220510_0800'),
    ]

    operations = [
    ]
