# Generated by Django 4.0.3 on 2022-03-29 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermissions_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_queue',
                'managed': False,
            },
        ),
    ]
