# Generated by Django 3.2.5 on 2022-04-22 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0004_userreactcourserev_userreactfacultyrev'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('user_level', models.IntegerField()),
                ('discarded_rev_count', models.IntegerField()),
                ('major', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
