# Generated by Django 4.0.2 on 2022-05-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220510_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='overall_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
