# Generated by Django 4.0.3 on 2022-05-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_merge_20220517_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfacultyrev',
            name='report_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
