# Generated by Django 4.0.3 on 2022-05-19 12:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_userfacultyrev_report_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfacultyrev',
            unique_together={('user', 'employee', 'review', 'course')},
        ),
    ]
