# Generated by Django 4.0.2 on 2022-05-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_employee_overall_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='exams_difficulty',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overall_rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='teaching_quality',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
