# Generated by Django 4.0.4 on 2022-05-28 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_usercourserev_course_tag_coursetags'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursetags',
            table='Course_tags',
        ),
    ]
