# Generated by Django 4.0.4 on 2022-05-28 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_coursetags_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeptRev',
            fields=[
                ('review', models.AutoField(primary_key=True, serialize=False)),
                ('overall_rating', models.IntegerField()),
                ('support', models.IntegerField()),
                ('activities', models.IntegerField()),
                ('upvotes', models.IntegerField(blank=True, null=True)),
                ('downvotes', models.IntegerField(blank=True, null=True)),
                ('report_count', models.IntegerField(blank=True, null=True)),
                ('student_thoughts', models.CharField(blank=True, max_length=500, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_dept_rev',
                'unique_together': {('user', 'department', 'review')},
            },
        ),
        migrations.DeleteModel(
            name='DeptGeneralcomments',
        ),
    ]
