# Generated by Django 4.0.2 on 2022-05-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userfacultyrev_unique_together_and_more'),
        ('main', '0006_alter_employee_exams_difficulty_and_more'),
    ]

    operations = [
    ]
