# Generated by Django 4.0.3 on 2022-05-21 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_alter_userfacultyrev_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='exams_difficulty',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='overall_rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='teaching_quality',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterUniqueTogether(
            name='userfacultyrev',
            unique_together={('user', 'employee', 'review')},
        ),
    ]
