# Generated by Django 4.0.4 on 2022-05-28 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_userdeptrev_delete_deptgeneralcomments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdeptrev',
            old_name='activities',
            new_name='activities_rating',
        ),
        migrations.RenameField(
            model_name='userdeptrev',
            old_name='support',
            new_name='support_rating',
        ),
    ]
