# Generated by Django 4.0.4 on 2022-05-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_activities_userdeptrev_activities_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfacultyrev',
            name='helpful',
            field=models.BooleanField(default=True),
        ),
    ]
