INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (34,'Assistant Professor','','Texas A&M University','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw170396.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (35,'Assistant Professor','','University of Miami','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw147692.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (36,'Associate Professor','','Syracuse University',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (37,'Assistant Professor','','Purdue University','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw233288.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (38,'Assistant Professor','Computer Security','University of Virginia','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw147701.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (39,'Assistant Professor','','NULL',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (40,'Professor','Theoretical Computer Science:Computer and Network Security','University of California','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw146842.png');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (41,'Professor','Computer Networks','Georgia Institute of Technology','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw147672.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (42,'Professor','Computer Architecture','University of Southern California','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw147674.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (43,'Associate Professor','Human Computer Interaction','Concordia University',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (44,'Professor','Data Mining:Security','Syracuse University','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw146844.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (45,'Assistant Professor','','NULL',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (46,'Associate Professor','Computer Networks','University of Southern California',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (47,'Assistant Professor','','NULL','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw110696.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (48,'Assistant Professor','','NULL','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw201884.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (49,'Assistant Professor','','NULL',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (50,'Professor','','Rensselaer Polytechnic Institute','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw146849.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (51,'Professor','','University of Washington','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw109916.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (52,'Professor','Parallel and Distributed Computing','Syracuse University','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw201881.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (53,'Assistant Professor','','NULL','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw147429.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (54,'Associate Professor','','North Carolina State University','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw201883.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (55,'Assistant Professor','','NULL',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (56,'Assistant Professor','','NULL','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw110698.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (57,'Assistant Professor','','NULL',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (58,'Assistant Professor','','NULL',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (59,'Assistant Professor','','University of Massachusetts Amherst','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw201885.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (60,'Associate Professor','','New Mexico State University','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw147665.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (61,'Professor','Computer Networks','University of Southern California','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw109661.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (62,'Professor','','The University of Iowa','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw201882.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (63,'Associate Professor','','University of Wisconsin-Madison','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw118248.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (64,'Assistant Professor','','Virginia Tech','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw146848.png');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (65,'Assistant Professor','Data Mining:Artificial Intelligence','NULL',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (66,'Associate Professor','','University of Southern California','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw109719.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (67,'Associate Professor','Computer Networks','University of Waterloo','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw146846.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (68,'Assistant Professor','','Syracuse University','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw201886.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (69,'Assistant Professor','','NULL',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (70,'Assistant Professor','Human Computer Interaction:Software Engineering','University of Colorado Boulder',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (71,'Associate Professor','','Northwestern University','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw109660.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (72,'Associate Professor','','Concordia University','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw108782.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (73,'Professor','','University of Southern California',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (74,'Assistant Professor','','University of California Irvine',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (75,'Associate Professor','Computer Architecture','Yale University','http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw147697.jpg');
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (76,'Assistant Professor','','NULL',NULL);