INSERT INTO Course (course, course_name) VALUES (0418106, 'Fortran');
INSERT INTO Course (course, course_name) VALUES (0418108, 'Computers and their Applications');
INSERT INTO Course (course, course_name) VALUES (0418111, 'Discrete Mathematics for Computer Science');
INSERT INTO Course (course, course_name) VALUES (0418123, 'Introduction to Computers');
INSERT INTO Course (course, course_name) VALUES (0418126, 'Computer Programming');
INSERT INTO Course (course, course_name) VALUES (0418141, 'Computer Programming I');
INSERT INTO Course (course, course_name) VALUES (0418142, 'Computer Programming II');
INSERT INTO Course (course, course_name) VALUES (0418201, 'Data Structures and Algorithms');
INSERT INTO Course (course, course_name) VALUES (0418211, 'Theory of Computation I');
INSERT INTO Course (course, course_name) VALUES (0418220, 'Programming in C and UNIX');
INSERT INTO Course (course, course_name) VALUES (0418221, 'Computer Systems');
INSERT INTO Course (course, course_name) VALUES (0418222, 'Systems Programming Laboratory');
INSERT INTO Course (course, course_name) VALUES (0418223, 'Systems Programming');
INSERT INTO Course (course, course_name) VALUES (0418301, 'Algorithm Design and Analysis');
INSERT INTO Course (course, course_name) VALUES (0418311, 'Numerical Computation');
INSERT INTO Course (course, course_name) VALUES (0418315, 'Theory of Computation II');
INSERT INTO Course (course, course_name) VALUES (0418321, 'Operating Systems');
INSERT INTO Course (course, course_name) VALUES (0418322, 'Computer Architecture');
INSERT INTO Course (course, course_name) VALUES (0418331, 'Computer Network');
INSERT INTO Course (course, course_name) VALUES (0418335, 'Web Programming');
INSERT INTO Course (course, course_name) VALUES (0418346, 'Declarative Programming');
INSERT INTO Course (course, course_name) VALUES (0418347, 'Compiler Design');
INSERT INTO Course (course, course_name) VALUES (0418365, 'Artificial Intelligence');
INSERT INTO Course (course, course_name) VALUES (0418390, 'Software Engineering');
INSERT INTO Course (course, course_name) VALUES (0418391, 'Fundamentals of Cloud Computing');
INSERT INTO Course (course, course_name) VALUES (0418415, 'Information Theory and Cryptography');
INSERT INTO Course (course, course_name) VALUES (0418416, 'Modeling and Performance Evaluation');
INSERT INTO Course (course, course_name) VALUES (0418425, 'Distributed and Parallel Systems');
INSERT INTO Course (course, course_name) VALUES (0418426, 'Embedded Microprocessor Systems');
INSERT INTO Course (course, course_name) VALUES (0418427, 'Computer Security and Privacy');
INSERT INTO Course (course, course_name) VALUES (0418455, 'Computer Graphics');
INSERT INTO Course (course, course_name) VALUES (0418466, 'Introduction to Machine Learning');
INSERT INTO Course (course, course_name) VALUES (0418470, 'Database Systems');
INSERT INTO Course (course, course_name) VALUES (0418475, 'Distributed Database Systems');
INSERT INTO Course (course, course_name) VALUES (0418490, 'Project');
INSERT INTO Course (course, course_name) VALUES (0418491, 'Capstone Project I');
INSERT INTO Course (course, course_name) VALUES (0418492, 'Capstone Project II');
INSERT INTO Course (course, course_name) VALUES (0418496, 'Topics in Computer Science I');
INSERT INTO Course (course, course_name) VALUES (0418497, 'Topics in Computer Science II');


