INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (77,'Assistant Professor','Machine Learning','University of Florida',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (78,'Assistant Professor','Web Applications and Services','Queen''s university',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (79,'Assistant Professor','Distributed Systems','McGill University',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (80,'Assistant Professor','Software Quality and Testing','University of Michigan',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (81,'Associate Professor','Health Informatics','University of Maryland',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (82,'Assistant Professor','Data Mining','George Mason University',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (83,'Assistant Professor','Artificial Intelligence','George Mason University',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (84,'Assistant Professor','Health Informatics','Georgia Institute of Technology',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (85,'Associate Professor','Data Mining','Queen’s University',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (86,'Associate Professor','Fuzzy Logic','Virginia Tech',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (87,'Associate Professor','Distributed Computing','Mororan Institute of Technology',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (88,'Professor','','University of Ottawa',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (89,'Assistant Professor','Data mining:Machine Learning','George Mason University',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (90,'Assistant Professor','Wireless Communications','Newcastle University',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (91,'Assistant Professor','Security','Southern Methodist University',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (92,'Professor','Graph Algorithms','University of Newcastle',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (93,'Assistant Professor','Security','Southern Methodist University',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (94,'Assistant Professor','Intrusion Detection Systems','University of Waterloo',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (95,'Professor','Statistics','University of Wyoming',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (96,'Assistant Professor','Data Mining:Cyber Security:Health Informatics','University of Maryland',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (97,'Assistant Professor','Internet-of-Things','University of California Irvine',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (98,'Assistant Professor','Web Services','The University of Western Ontario',NULL);
INSERT INTO Professor(faculty_id, prof_rank,research_area,phd_from,image) VALUES (99,'Assistant Professor','Computer Graphics:Human Computer Interaction','University of Waterloo',NULL);
