INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Abbas','Fairouz', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw170396.jpg','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Abdulaziz','Boujarwah', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw147692.jpg','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Abdullah','Almutawa', 'https://www.cs.ku.edu.kw/wp-content/uploads/2020/04/default-profile.png','Faculty', 'Associate Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Abdullah','Alshaibani', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw233288.jpg','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Ameer','Mohammed', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw147701.jpg','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Ammar','Alhusaini', '','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Anastasios','Dimitriou', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw146842.png','Faculty', 'Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Anwar','Alyatama', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw147672.jpg','Faculty', 'Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Asaad','Alrashed', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw147674.jpg','Faculty', 'Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Asmaa','Alsumait', '','Faculty', 'Associate Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Ayed','Salman', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw146844.jpg','Faculty', 'Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Buthainah','Alkazemi', '','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Ebrahim','Alrashed', '','Faculty', 'Associate Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Eman','Alotaibi', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw110696.jpg','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Faridah','Ali', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw201884.jpg','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Fatma','Alali', '','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Fawaz','Alanzi', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw146849.jpg','Faculty', 'Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Hamed','Alazmi', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw109916.jpg','Faculty', 'Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Imtiaz','Ahmed', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw201881.jpg','Faculty', 'Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Jassim','Aljuraidan', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw147429.jpg','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Khaled','Alsaqabi', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw201883.jpg','Faculty', 'Associate Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Khaled','Alzamel', '','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Khaled','Hadi', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw110698.jpg','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Lulwa','Alhubail', '','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Maha','Faisal', '','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Mahmoud','Bennaser', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw201885.jpg','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Mansour','Jaragh', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw147665.jpg','Faculty', 'Associate Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Maytham','Safar', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw109661.jpg','Faculty', 'Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Mehmet','Karaata', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw201882.jpg','Faculty', 'Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Mohammad','Alfailakawi', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw118248.jpg','Faculty', 'Associate Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Mohammad','Alkandari', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw146848.png','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Mohammad','Allaho', '','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Mohammad','Alshayeji', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw109719.jpg','Faculty', 'Associate Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Mohammad','Awad', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw146846.jpg','Faculty', 'Associate Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Mohammad','Jeragh', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw201886.jpg','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Munirah','Almatouq', '','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Reem','Albaghli', '','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Sabah','Alfedaghi', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw109660.jpg','Faculty', 'Associate Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Saeed','Abed', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw108782.jpg','Faculty', 'Associate Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Sami','Habib', '','Faculty', 'Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Shouq','Alsubaihi', '','Faculty', 'Assistant Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Sobeeh','Almukhaizim', 'http://kuwebcont.ku.edu.kw/cs/groups/coep/documents/ku_content/kuw147697.jpg','Faculty', 'Associate Professor' ,1612);
INSERT INTO Employee (fname, lname, image, main_rank, sub_rank, department_id) VALUES ('Sultan','Alharbi', '','Faculty', 'Assistant Professor' ,1612);

