INSERT INTO Course (course, course_name) VALUES (1830253, 'Technical Writing');
INSERT INTO Course (course, course_name) VALUES (1830101, 'Introduction to IS');
INSERT INTO Course (course, course_name) VALUES (1830115, 'Computing Foundations');
INSERT INTO Course (course, course_name) VALUES (1830210, 'Computational Methods');
INSERT INTO Course (course, course_name) VALUES (1830240, 'Programming & Problem Solving');
INSERT INTO Course (course, course_name) VALUES (1830241, 'Data Structures');
INSERT INTO Course (course, course_name) VALUES (1830321, 'Database Systems I');
INSERT INTO Course (course, course_name) VALUES (1830331, 'IS Theory & Practice');
INSERT INTO Course (course, course_name) VALUES (1830340, 'Web Programsming');
INSERT INTO Course (course, course_name) VALUES (1830350, 'Networks & Telecommunication');
INSERT INTO Course (course, course_name) VALUES (1830353, 'Information Security Systems');
INSERT INTO Course (course, course_name) VALUES (1830357, 'Operating Systems & File System Organization');
INSERT INTO Course (course, course_name) VALUES (1830363, 'Computer Organization');
INSERT INTO Course (course, course_name) VALUES (1830495, 'Internship');
INSERT INTO Course (course, course_name) VALUES (1830499, 'Capstone Project');
INSERT INTO Course (course, course_name) VALUES (1830480, 'IS Development');
INSERT INTO Course (course, course_name) VALUES (1830380, 'Introduction to Management IS');
INSERT INTO Course (course, course_name) VALUES (1830423, 'Internet Databases');
INSERT INTO Course (course, course_name) VALUES (1830440, 'Web Programming II');
INSERT INTO Course (course, course_name) VALUES (1830470, 'Multimedia Design & Scripting');
INSERT INTO Course (course, course_name) VALUES (1830471, 'Interactive 3D Graphics Modeling');
INSERT INTO Course (course, course_name) VALUES (1830472, 'Introduction to VRML');
INSERT INTO Course (course, course_name) VALUES (1830475, 'Geographical Information Systems');
INSERT INTO Course (course, course_name) VALUES (1830482, 'Web Management');
