INSERT INTO Course VALUES (41091 , 'Pre-calculus');
INSERT INTO Course VALUES (410100, 'Elementary Mathematics');
INSERT INTO Course VALUES (410101, 'Calculus I');
INSERT INTO Course VALUES (410102, 'Calculus II');
INSERT INTO Course VALUES (410103, 'Biomathematics INSERT INTO Course VALUES (Only for Biology students)');
INSERT INTO Course VALUES (410105, 'Applied Calculus INSERT INTO Course VALUES (Only for students from the College of women)');
INSERT INTO Course VALUES (410111, 'Introductory Linear Algebra');
INSERT INTO Course VALUES (410115, 'Finite Mathematics INSERT INTO Course VALUES (Non Mathematics Major)'); 
INSERT INTO Course VALUES (410211, 'Calculus III'); 
INSERT INTO Course VALUES (410226, 'Euclidean Plane Geometry');
INSERT INTO Course VALUES (410240, 'Ordinary Differential Equations'); 
INSERT INTO Course VALUES (410250, 'Introduction to the Foundations of Mathematics'); 
INSERT INTO Course VALUES (410261, 'Introduction to Abstract Algebra I'); 
INSERT INTO Course VALUES (410262, 'Introduction to Abstract Algebra II'); 
INSERT INTO Course VALUES (410313, 'Applied Mathematical Analysis'); 
INSERT INTO Course VALUES (410315, 'Mathematical Electromagnetic Theory');
INSERT INTO Course VALUES (410316, 'Elements of Mathematical Modelling');
INSERT INTO Course VALUES (410325, 'Combinatorics');
INSERT INTO Course VALUES (410326, 'Graph Theory');
INSERT INTO Course VALUES (410327, 'Theory of Numbers');
INSERT INTO Course VALUES (410329, 'Introduction to Real Analysis');
INSERT INTO Course VALUES (410330, 'Functions of Complex Variables');
INSERT INTO Course VALUES (410340, 'Theory of Differential Equations'); 
INSERT INTO Course VALUES (410343, 'Classical Mechanics');
INSERT INTO Course VALUES (410345,'Abstract Algebra');
INSERT INTO Course VALUES (410346, 'Group Theory');
INSERT INTO Course VALUES (410352, 'Numerical Analysis');
INSERT INTO Course VALUES (410354, 'Methods in Applied Mathematics');
INSERT INTO Course VALUES (410355, 'Operational Mathematics');
INSERT INTO Course VALUES (410361, 'Theoretical Fluid Dynamics');
INSERT INTO Course VALUES (410362,  'Computational Linear Algebra');
INSERT INTO Course VALUES (410363, 'Advanced Linear Algebra'); 
INSERT INTO Course VALUES (410370, 'Geometry I');
INSERT INTO Course VALUES (410375, 'Introduction to Topology');
INSERT INTO Course VALUES (410401, 'Analysis');
INSERT INTO Course VALUES (410402, 'Set Theory');
INSERT INTO Course VALUES (410403, 'Advanced Linesr Algebra'); 
INSERT INTO Course VALUES (410404, 'Analysis of Functions of Several Variables');
INSERT INTO Course VALUES (410406, 'Algebraic Coding Theory');
INSERT INTO Course VALUES (410407, 'Tensor Analysis'); 
INSERT INTO Course VALUES (410408, 'Topology');
INSERT INTO Course VALUES (410409, 'Geometry II');
INSERT INTO Course VALUES (410410, 'Theory of Relativity');
INSERT INTO Course VALUES (410412, 'Theory of Elasticity');;
INSERT INTO Course VALUES (410415, 'Partial Differential Equations');
INSERT INTO Course VALUES (410416, 'Mathematical Modelling');
INSERT INTO Course VALUES (410420, 'Introduction to Dynamical Systems and Chaos');
INSERT INTO Course VALUES (410438, 'Applications of Graph Theory'); 
INSERT INTO Course VALUES (410440, 'Integral Equations'); 
INSERT INTO Course VALUES (410450, 'Ring Theory'); 
INSERT INTO Course VALUES (410454, 'Advanced Methods in Applied Mathematics');
INSERT INTO Course VALUES (410468, 'Numerical Ordinary Differential Equations');
INSERT INTO Course VALUES (410469, 'Numerical Partial Differential Equations');
INSERT INTO Course VALUES (410470, 'Calculus of Variations'); 
INSERT INTO Course VALUES (410480, 'Differential Geometry');
INSERT INTO Course VALUES (410481, 'Functional Analysis');
INSERT INTO Course VALUES (410485, 'Finite Planes');
INSERT INTO Course VALUES (410495, 'Mathematical Logic');
