INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Hani', 'Farran');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Ismail', 'Taqi');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Marian', 'Deaconescu');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Michael', 'Johnson');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Nejib', 'Smaoui');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Salem', 'Al-Yaqoub');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Abdullah', 'Alazemi');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Ahmad', 'Karaballi');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Albert', 'Borbely');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Ali ', 'Kanso');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Anton', 'Betten');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Aurelian', 'Bejancu');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Bader ', 'Al-Shammary');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Boudjemaa', 'Anchouche');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Boumediene', 'Chentouf');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Fares', 'Alazemi');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Fathi', 'Saidi');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Fuat', 'Gurcan');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Khaled', 'Qazaqzeh');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Khalifa', 'Es-Sebaiy');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Latif', 'Hanna');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Mamad', 'Ghebleh');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Milica', 'Anđelić');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Zafer', 'Mahmud');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Abdulaziz', 'Alsenafi');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Abdullah', 'Alshammari');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Abdelhameed', 'Abdo');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Ahood', 'Al-Jasser');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Ameena', 'Alzaidan');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Hamid', 'Said');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Hessah', 'Al-Motairi');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Kyriakos', 'Papadopoulos');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Maryam', 'Alkandari');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Mishari', 'Al-Foraih');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Saleh', 'Baqer');
  


INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Abdulrahman', 'Mubarak');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Adnan', 'Al-Sayed');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Alaa', 'Alqaderi');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Amal', 'Alrashdan');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Ayman', 'EzzElarab');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Baba', 'Amoro');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Hameed', 'Al-Fahad');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Maale', 'Al-Motairi');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Mayada', 'Yousif');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Muna', 'Aljazzaf');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Rayouf', 'Alsahli');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Samer', 'Al-Sahhar');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Shorouq', 'Al-Ghunaim');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Wafa', 'Abdulrahman');
INSERT INTO Faculty(dept_code, fname,lname) VALUES (410, 'Yousef', 'Alenazi');
